#!/usr/bin/env python3
"""Convert The Last Room's PNG cover into an LVGL 9 RGB565 C resource."""

from pathlib import Path
import struct
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/images/escape-room-the-last-room-cover-startup-v3-240x320.png"
OUTPUT = ROOT / "assets/images/game_cover_startup.c"
EXPECTED_SIZE = (240, 320)


def read_bmp_rgb565(path: Path) -> tuple[int, int, bytes]:
    data = path.read_bytes()
    if data[:2] != b"BM":
        raise ValueError("sips did not produce a BMP file")
    pixel_offset = struct.unpack_from("<I", data, 10)[0]
    width, height = struct.unpack_from("<ii", data, 18)
    bits_per_pixel = struct.unpack_from("<H", data, 28)[0]
    if width <= 0 or height == 0 or bits_per_pixel != 24:
        raise ValueError("expected a 24-bit BMP with non-zero dimensions")

    absolute_height = abs(height)
    row_stride = (width * 3 + 3) & ~3
    if len(data) < pixel_offset + row_stride * absolute_height:
        raise ValueError("BMP pixel data is truncated")

    rows = range(absolute_height) if height < 0 else range(absolute_height - 1, -1, -1)
    pixels = bytearray()
    for row in rows:
        row_start = pixel_offset + row * row_stride
        for offset in range(row_start, row_start + width * 3, 3):
            blue, green, red = data[offset:offset + 3]
            rgb565 = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
            pixels.extend((rgb565 & 0xFF, rgb565 >> 8))
    return width, absolute_height, bytes(pixels)


def write_c_resource(width: int, height: int, pixels: bytes) -> None:
    rows = [", ".join(f"0x{value:02X}" for value in pixels[index:index + 12])
            for index in range(0, len(pixels), 12)]
    body = ",\n    ".join(rows)
    OUTPUT.write_text(
        "/* Generated by tools/generate_game_cover.py. Do not edit manually. */\n"
        "#include \"lvgl.h\"\n\n"
        "const LV_ATTRIBUTE_LARGE_CONST uint8_t game_cover_startup_map[] = {\n"
        f"    {body}\n"
        "};\n\n"
        "const lv_image_dsc_t game_cover_startup = {\n"
        "    .header = {\n"
        "        .magic = LV_IMAGE_HEADER_MAGIC,\n"
        "        .cf = LV_COLOR_FORMAT_RGB565,\n"
        "        .flags = 0,\n"
        f"        .w = {width},\n"
        f"        .h = {height},\n"
        f"        .stride = {width * 2},\n"
        "        .reserved_2 = 0,\n"
        "    },\n"
        "    .data_size = sizeof(game_cover_startup_map),\n"
        "    .data = game_cover_startup_map,\n"
        "    .reserved = NULL,\n"
        "    .reserved_2 = NULL,\n"
        "};\n",
        encoding="utf-8",
    )


def main() -> None:
    if not SOURCE.is_file():
        raise SystemExit(f"source image is missing: {SOURCE.relative_to(ROOT)}")
    with tempfile.TemporaryDirectory(prefix="the-last-room-cover-") as directory:
        bmp = Path(directory) / "cover.bmp"
        subprocess.run(
            ["sips", "-s", "format", "bmp", str(SOURCE), "--out", str(bmp)],
            check=True,
            stdout=subprocess.DEVNULL,
        )
        width, height, pixels = read_bmp_rgb565(bmp)
    if (width, height) != EXPECTED_SIZE:
        raise SystemExit(f"expected {EXPECTED_SIZE[0]}x{EXPECTED_SIZE[1]}, got {width}x{height}")
    write_c_resource(width, height, pixels)
    print(f"generated {OUTPUT.relative_to(ROOT)} ({len(pixels)} bytes RGB565)")


if __name__ == "__main__":
    main()
